#!/user/bin/env bash
#sshclient configuration
  PasswordAuthentication no
  IdentityFile ~/.ssh/school
  SendEnv LANG LC_*
  HashKnownHosts yes
  GSSAPIAuthentication yes
  GSSAPIDelegateCredentials no
